### ISSUE TITLE
PTY is not supported on Windows

### ISSUE THREAD

**Issue by snowe2010** [sleewoo/traveler#2]
I'm receiving this error on windows. 

```
λ ~\Docu\reco\tool\portal-bdd traveler init
C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- pty (LoadError)
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/traveler-0.0.1/lib/traveler.rb:2:in `<top (required)>'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/traveler-0.0.1/bin/traveler:3:in `<top (required)>'
        from C:/Ruby21-x64/bin/traveler:23:in `load'
        from C:/Ruby21-x64/bin/traveler:23:in `<main>'
```

PTY is not supported on windows. Other gems resolve this by delaying the require for 'pty'

**Comment by sleewoo** [comment]
No windows support for now, i just can not afford it.
Waiting for some +1s on this feature request and contributors with windows machines :)

**Comment by snowe2010** [comment]
What steps does traveler perform that might not work on Windows. I can try to contribute.

**Comment by canvural** [comment]
+1 Windows support would be awesome. 

I can help too.
